frontend:
  - changed-files:
    - any-glob-to-any-file: 'src/frontend/**'

bff:
  - changed-files:
    - any-glob-to-any-file: 'src/bff/**'

shared:
  - changed-files:
    - any-glob-to-any-file: 'src/shared/**'

infrastructure:
  - changed-files:
    - any-glob-to-any-file: 'infra/**'

ci-cd:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'
